services:
  db:
    image: postgres:14
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: embarca_development
      DATABASE_NAME: brazil_cities

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: brazil_cities
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  node_modules:
